# Generated by Django 4.0 on 2021-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_game_user_total_games_user_win_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(default='none', upload_to='photo/'),
        ),
    ]
