# Generated by Django 4.0 on 2021-12-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_game_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='multiplayer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='single_player',
        ),
    ]
